from browser import document, timer
import random

idk = document["idk"]
btn = document["btn"]
body = document["body"]

vety = [
    "Zvládneš viac, než si myslíš.",
    "Každý malý krok ťa približuje k veľkému cieľu.",
    "Tvoje úsilie má hodnotu, aj keď výsledky ešte nevidíš.",
    "Si silnejší/-ia, ako sa dnes cítiš.",
    "Každý deň je nová šanca začať lepšie.",
    "Máš v sebe všetko, čo potrebuješ na úspech.",
    "Aj neúspech je súčasť cesty k víťazstvu.",
    "Odvaha nie je absencia strachu, ale rozhodnutie pokračovať napriek nemu.",
    "Máš právo rásť svojím tempom.",
    "Ver si - už tým robíš prvý krok k zmene.",
    "Každý nový začiatok je príležitosťou ukázať svoju silu.",
    "Máš schopnosť meniť svoj život krok za krokom.",
    "Aj malé víťazstvá sú dôležité - osláv ich.",
    "To, že je to ťažké, neznamená, že to nezvládneš.",
    "Tvoja snaha sa raz zúročí, aj keď to teraz tak nevyzerá.",
    "Dôveruj si - už si prekonal/-a mnoho prekážok.",
    "Si na dobrej ceste, pokračuj.",
    "Každý deň môžeš byť o kúsok lepšou verziou seba.",
    "Neboj sa urobiť chybu - vďaka nej rastieš.",
    "Zaslúžiš si pokoj, radosť a úspech.",
    "Každý deň prináša nové možnosti.",
    "Ver, že dobré veci sú na ceste.",
    "Máš hodnotu presne taký/á, aký/á si.",
    "Pokračuj - tvoja vytrvalosť ťa dovedie tam, kam chceš.",
    "Každá skúsenosť ťa učí niečo cenné.",
    "Máš právo byť na seba hrdý/á.",
    "Aj malé kroky vedú k veľkým zmenám.",
    "Si schopný/á prekonať akúkoľvek výzvu.",
    "Tvoj vnútorný pokoj je dôležitý - chráň ho.",
    "Tvoje sny stoja za to, aby si o ne bojoval/a.",
    "Si dôležitý/á pre svet okolo teba.",
    "Neboj sa začať znovu - môže to viesť k lepšiemu.",
    "Máš silu zvládnuť aj náročné dni.",
    "Každý posun dopredu je úspech.",
    "Si schopný/á tvoriť krásne veci.",
    "Tvoje úsilie sa raz prejaví.",
    "Všetko, čo potrebuješ, si už v sebe nesieš.",
    "Si viac ako tvoje obavy.",
    "Dovoľ si rásť a meniť sa.",
    "Máš na to, aby si dosiahol/a svoje ciele.",
    "Si odolnejší/-ia, než si uvedomuješ.",
    "Každý deň je šanca byť o krok ďalej.",
    "Si dôležitý/á a jedinečný/á.",
    "Aj malé zlepšenia sú veľkým pokrokom.",
    "Robíš to najlepšie, čo vieš - a to stačí.",
    "Tvoje sny sú reálne a dosiahnuteľné.",
    "Ver procesu, aj keď nie je hneď vidieť výsledok.",
    "Si schopný/á tvoriť pozitívnu zmenu.",
    "Neboj sa veriť si viac.",
    "Si hodný/á lásky, rešpektu aj pokoja.",
    "Držíš sa, aj keď je to ťažké - to je sila.",
    "Máš pred sebou veľa krásnych dní.",
    "Nikto nemôže nahradiť tvoju jedinečnosť.",
    "Urob si priestor pre svoje šťastie.",
    "Tvoja námaha má význam.",
    "Môžeš byť hrdý/á na to, kam si sa dostal/a.",
    "Všetko, čo si prekonal/a, ťa posilnilo.",
    "Máš právo cítiť sa dobre.",
    "Pokoj začína v tebe.",
    "Každý deň sa môžeš rozhodnúť pre nový smer.",
    "Si silný/á, aj keď sa tak necítiš.",
    "Tvoje úspechy sú bližšie, než si myslíš.",
    "Handlová",
    "Zaslúžiš si oddych aj uznanie.",
    "Neboj sa požiadať o podporu - je to múdre.",
    "Každá prekážka môže byť príležitosťou.",
    "Si tvorcom svojej budúcnosti.",
    "Nezabúdaj, že rastieš aj v tichu.",
    "Tvoje úsilie je obdivuhodné.",
    "Máš silu urobiť správne kroky.",
    "Nezastavuj sa - ideš dobrým smerom.",
    "Tvoje priania sú dôležité.",
    "Aj malá odvaha má veľký dopad.",
    "Si viac, než tvoje pochybnosti.",
    "Pracuješ na sebe a to je krásne.",
    "Každá nová skúsenosť ti pridáva múdrosť.",
    "Máš právo byť šťastný/á.",
    "Ver, že všetko sa dá zvládnuť krok za krokom.",
    "Neboj sa robiť veci po svojom.",
    "Máš schopnosť prinášať svetlo aj druhým.",
    "Tvoje sny majú význam - neodkladaj ich.",
    "Si odvážny/á, aj keď kráčaš malými krokmi.",
    "Každý deň môžeš začať nanovo.",
    "Máš v sebe veľkú silu ukrytú v tichosti.",
    "Ver si viac - zaslúžiš si to.",
    "Tvoja cesta je jedinečná a cenná.",
    "Máš právo hľadať, čo ti robí dobre.",
    "Vážiš si seba a to je základ všetkého.",
    "Dokážeš zvládnuť aj to, čo sa dnes zdá náročné.",
    "Tvoja energia dokáže meniť svet okolo teba.",
    "Si stále v procese rastu - a to je krásne.",
    "V každom dni je niečo dobré - stačí to nájsť.",
    "Tvoje srdce vie, kam chce ísť - počúvaj ho.",
    "Agartha",
    "Zaslúžiš si čas pre seba.",
    "Máš moc rozhodovať o svojom živote.",
    "Si silný/á, aj keď padáš - pretože sa stále dvíhaš.",
    "Nič nie je malé, ak je to úprimné.",
    "Tvoj úsmev dokáže zmeniť deň niekomu inému.",
    "Si na správnej ceste, aj keď ideš pomaly.",
    "Život ti ponúkne nové šance, ver tomu.",
    "Si tu z dôvodu - a to je samo o sebe nádherné.",
    "Ak chceš môžem ti vygewnerovať ďalších 10 povzbudivých viet."
]

farby = ["#FF5733", "#33FF57", "#3357FF", "#F333FF", "#33FFF5", "#F5FF33", "#FF33A8", "#A833FF"]

def povzbudi(event):
    veta = random.randrange(len(vety))
    farba = random.randrange(len(farby))
    idk.text = vety[veta]
    body.style.backgroundColor = farby[farba]

btn.bind("click", povzbudi)